/**********************************************************************************************************************
 * \file SPI_DMA.h
 * \copyright Copyright (C) Infineon Technologies AG 2019
 *
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 *
 * Boost Software License - Version 1.0 - August 17th, 2003
 *
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all
 * derivative works of the Software, unless such copies or derivative works are solely in the form of
 * machine-executable object code generated by a source language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 * IN THE SOFTWARE.
 *********************************************************************************************************************/

#ifndef SPI_DMA_H_
#define SPI_DMA_H_

/*********************************************************************************************************************/
/*-----------------------------------------------------Includes------------------------------------------------------*/
/*********************************************************************************************************************/
#include "IfxQspi_SpiMaster.h"
#include "Ifx_Types.h"

/*********************************************************************************************************************/
/*------------------------------------------------------Macros-------------------------------------------------------*/
/*********************************************************************************************************************/
#define NUM_LEDS          4
#define SPI_BYTES_PER_LED 9
#define RESET_BYTES       60
#define SPI_BUFFER_SIZE   (NUM_LEDS * SPI_BYTES_PER_LED) + RESET_BYTES /* SPI Buffer size */

/*********************************************************************************************************************/
/*-------------------------------------------------Data Structures---------------------------------------------------*/
/*********************************************************************************************************************/

typedef struct
{
  IfxQspi_SpiMaster spiMaster;                /* QSPI Master handle           */
  IfxQspi_SpiMaster_Channel spiMasterChannel; /* QSPI Master Channel handle   */
} qspiDma;

/*********************************************************************************************************************/
/*------------------------------------------------Function Prototypes------------------------------------------------*/
/*********************************************************************************************************************/
void setNeopixelColor(uint32 ledIndex, uint8 red, uint8 green, uint8 blue);
void setNeopixelColorHSV(uint32 ledIndex, uint8 hue, uint8 sat, uint8 val);
void shiftLedsForward(uint8 r, uint8 g, uint8 b);
void shiftLedsForwardHSV(int hue, int sat, int val);
void shiftLedsBackward(uint8 r, uint8 g, uint8 b);
void shiftLedsBackwardHSV(int hue, int sat, int val);
void convertHSVtoRGB(float h, float s, float v, uint8 *r, uint8 *g, uint8 *b);
void initNeopixel(void);                     // 초기 설정
void transmitNeopixel(void);                 // 현재 설정된 색 전송
void setAllLEDColorHSV(int h, int s, int v); // hue(색조): 0-360, saturation(채도): 0-100, value(밝기): 0-100

#endif /* SPI_DMA_H_ */