/**********************************************************************************************************************
 * \file SPI_DMA.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 *
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 *
 * Boost Software License - Version 1.0 - August 17th, 2003
 *
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all
 * derivative works of the Software, unless such copies or derivative works are solely in the form of
 * machine-executable object code generated by a source language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 * IN THE SOFTWARE.
 *********************************************************************************************************************/

/*********************************************************************************************************************/
/*-----------------------------------------------------Includes------------------------------------------------------*/
/*********************************************************************************************************************/
#include "Base_Neopixel.h"
#include "IfxPort.h"
#include <math.h>

/*********************************************************************************************************************/
/*------------------------------------------------------Macros-------------------------------------------------------*/
/*********************************************************************************************************************/
#define QSPI1_MASTER &MODULE_QSPI1 /* SPI Master Hardware module                       */
#define QSPI3_SLAVE  &MODULE_QSPI3 /* SPI Slave Hardware module                        */

#define ISR_PRIORITY_QSPI1_TX 1  /* Define the QSPI1 transmit interrupt priority     */
#define ISR_PRIORITY_QSPI1_RX 2  /* Define the QSPI1 receive interrupt priority      */
#define ISR_PRIORITY_QSPI1_ER 10 /* Define the QSPI1 error interrupt priority        */

#define ISR_PRIORITY_QSPI3_TX 3  /* Define the QSPI3 transmit interrupt priority     */
#define ISR_PRIORITY_QSPI3_RX 4  /* Define the QSPI3 receive interrupt priority      */
#define ISR_PRIORITY_QSPI3_ER 11 /* Define the QSPI3 error interrupt priority        */

#define ISR_PRIORITY_DMA_CH1 50 /* Define the DMA channel1 interrupt priority       */
#define ISR_PRIORITY_DMA_CH2 51 /* Define the DMA channel2 interrupt priority       */
#define ISR_PRIORITY_DMA_CH3 52 /* Define the DMA channel3 interrupt priority       */
#define ISR_PRIORITY_DMA_CH4 53 /* Define the DMA channel4 interrupt priority       */

#define ISR_PROVIDER_QSPI1 IfxSrc_Tos_cpu0 /* Define the QSPI1 interrupt provider              */
#define ISR_PROVIDER_QSPI3 IfxSrc_Tos_cpu0 /* Define the QSPI3 interrupt provider              */

#define ISR_PROVIDER_DMA_CH1 IfxSrc_Tos_cpu0 /* Define the DMA Channel1 interrupt provider       */
#define ISR_PROVIDER_DMA_CH2 IfxSrc_Tos_cpu0 /* Define the DMA Channel2 interrupt provider       */
#define ISR_PROVIDER_DMA_CH3 IfxSrc_Tos_cpu0 /* Define the DMA Channel3 interrupt provider       */
#define ISR_PROVIDER_DMA_CH4 IfxSrc_Tos_cpu0 /* Define the DMA Channel4 interrupt provider       */

#define MASTER_CHANNEL_BAUDRATE 2400000 /* Master channel baud rate                         */

/*********************************************************************************************************************/
/*-------------------------------------------------Global variables--------------------------------------------------*/
/*********************************************************************************************************************/
static qspiDma g_qspiDma; /* Global handle for QSPI communication             */
static uint8 spiTxBuffer[SPI_BUFFER_SIZE];

/*********************************************************************************************************************/
/*------------------------------------------------Function Prototypes------------------------------------------------*/
/*********************************************************************************************************************/
static void initQSPI1Master(void);
static void initQSPI1MasterChannel(void);
static void initQSPI(void);
void setNeopixelColor(uint32 ledIndex, uint8 red, uint8 green, uint8 blue);
void convertHSVtoRGB(float h, float s, float v, uint8 *r, uint8 *g, uint8 *b);

/*********************************************************************************************************************/
/*---------------------------------------------Function Implementations----------------------------------------------*/
/*********************************************************************************************************************/
IFX_INTERRUPT(QSPI1ErrorISR, 0, ISR_PRIORITY_QSPI1_ER); /* SPI Master Error Interrupt definition            */
IFX_INTERRUPT(DMAChn1ISR, 0, ISR_PRIORITY_DMA_CH1);     /* DMA Channel 1 Interrupt definition               */
IFX_INTERRUPT(DMAChn2ISR, 0, ISR_PRIORITY_DMA_CH2);     /* DMA Channel 2 Interrupt definition               */
IFX_INTERRUPT(DMAChn3ISR, 0, ISR_PRIORITY_DMA_CH3);     /* DMA Channel 3 Interrupt definition               */
IFX_INTERRUPT(DMAChn4ISR, 0, ISR_PRIORITY_DMA_CH4);     /* DMA Channel 4 Interrupt definition               */

/* Handle QSPI1 Error interrupt */
void QSPI1ErrorISR(void)
{
  IfxCpu_enableInterrupts();
  IfxQspi_SpiMaster_isrError(&g_qspiDma.spiMaster);
}

/* Handle DMA Channel 1 interrupt */
void DMAChn1ISR(void)
{
  IfxCpu_enableInterrupts();
  IfxQspi_SpiMaster_isrDmaTransmit(&g_qspiDma.spiMaster);
}

/* Handle DMA Channel 2 interrupt */
void DMAChn2ISR(void)
{
  IfxCpu_enableInterrupts();
  IfxQspi_SpiMaster_isrDmaReceive(&g_qspiDma.spiMaster);
}

/* This function initializes QSPI1 in master mode */
static void initQSPI1Master(void)
{
  IfxQspi_SpiMaster_Config spiMasterConfig; /* Define the Master Configuration          */

  IfxQspi_SpiMaster_initModuleConfig(&spiMasterConfig, QSPI1_MASTER); /* Initialize it with default values        */

  const IfxQspi_SpiMaster_Pins qspi1Masterpins = {
      NULL_PTR, IfxPort_OutputMode_pushPull,                 /* SCLK Pin                          (CLK)  */
      &IfxQspi1_MTSR_P10_3_OUT, IfxPort_OutputMode_pushPull, /* Master Transmit Slave Receive Pin (MOSI) */
      NULL_PTR, IfxPort_InputMode_pullDown,                  /* Master Receive Slave Transmit Pin (MISO) */
      IfxPort_PadDriver_cmosAutomotiveSpeed3                 /* Pad driver mode                          */
  };
  spiMasterConfig.pins = &qspi1Masterpins; /* Assign Master Pins                       */

  spiMasterConfig.dma.useDma = TRUE;
  spiMasterConfig.dma.txDmaChannelId = IfxDma_ChannelId_1;
  spiMasterConfig.dma.rxDmaChannelId = IfxDma_ChannelId_2;

  spiMasterConfig.txPriority = ISR_PRIORITY_DMA_CH1;
  spiMasterConfig.rxPriority = ISR_PRIORITY_DMA_CH2;
  spiMasterConfig.erPriority = ISR_PRIORITY_QSPI1_ER;
  spiMasterConfig.isrProvider = ISR_PROVIDER_QSPI1;

  /* Initialize the QSPI Master module using the user configuration */
  IfxQspi_SpiMaster_initModule(&g_qspiDma.spiMaster, &spiMasterConfig);
}

/*  This function initializes QSPI1 channel. */
static void initQSPI1MasterChannel(void)
{
  IfxQspi_SpiMaster_ChannelConfig spiMasterChannelConfig; /* Define the Master Channel Configuration  */

  IfxQspi_SpiMaster_initChannelConfig(&spiMasterChannelConfig, &g_qspiDma.spiMaster); /* Initialize it with default values */

  spiMasterChannelConfig.ch.baudrate = MASTER_CHANNEL_BAUDRATE; /* Set SCLK frequency to 1 MHz              */

  const IfxQspi_SpiMaster_Output qspi1SlaveSelectQspi3 = {
      &IfxQspi1_SLSO9_P10_5_OUT, IfxPort_OutputMode_pushPull, /* Slave Select Pin (CS)                    */
      IfxPort_PadDriver_cmosAutomotiveSpeed1                  /* Pad driver mode                          */
  };
  spiMasterChannelConfig.sls.output = qspi1SlaveSelectQspi3;

  /* Initialize the QSPI Master channel using the user configuration */
  IfxQspi_SpiMaster_initChannel(&g_qspiDma.spiMasterChannel, &spiMasterChannelConfig);
}

/* This function initializes the QSPI modules */
static void initQSPI(void)
{
  /* Secondly initialize the Master */
  initQSPI1Master();
  initQSPI1MasterChannel();
}

// 특정 LED의 색상을 버퍼에 기록하는 함수
void setNeopixelColor(uint32 ledIndex, uint8 red, uint8 green, uint8 blue)
{
  if (ledIndex >= NUM_LEDS) return;

  // Neopixel은 G -> R -> B 순서로 전송합니다.
  uint32 grbColor = (green << 16) | (red << 8) | blue;
  uint32 bufferIndex = ledIndex * SPI_BYTES_PER_LED;

  uint8 bytePattern = 0;
  uint8 bitCount = 0;

  // 24비트 데이터를 순회하며 SPI 비트 패턴 생성
  for (int i = 23; i >= 0; i--)
  {
    uint8 bitValue = (grbColor >> i) & 0x01;

    // 3비트 패턴 결정 (1 -> 110, 0 -> 100)
    uint8 pattern = bitValue ? 0x06 : 0x04;

    // 3비트 패턴을 8비트(1바이트) 배열로 패킹하는 로직
    for (int p = 2; p >= 0; p--)
    {
      bytePattern <<= 1;
      bytePattern |= ((pattern >> p) & 0x01);
      bitCount++;

      if (bitCount == 8)
      {
        spiTxBuffer[bufferIndex++] = bytePattern;
        bytePattern = 0;
        bitCount = 0;
      }
    }
  }
}

void setNeopixelColorHSV(uint32 ledIndex, uint8 hue, uint8 sat, uint8 val)
{
  uint8 r, g, b;
  convertHSVtoRGB(hue, sat, val, &r, &g, &b);
  setNeopixelColor(ledIndex, r, g, b);
}

// LED 색상을 뒤로 한 칸씩 미는 함수 (예: 0번 -> 1번, 1번 -> 2번)
void shiftLedsForward(uint8 r, uint8 g, uint8 b)
{
  // 덮어쓰기를 방지하기 위해 배열의 뒤에서부터 앞으로 복사를 진행합니다.
  for (int i = NUM_LEDS - 1; i > 0; i--)
  {
    uint32 destIndex = i * SPI_BYTES_PER_LED;
    uint32 srcIndex = (i - 1) * SPI_BYTES_PER_LED;

    for (int j = 0; j < SPI_BYTES_PER_LED; j++)
    {
      spiTxBuffer[destIndex + j] = spiTxBuffer[srcIndex + j];
    }
  }
  setNeopixelColor(0, r, g, b);
}

void shiftLedsForwardHSV(int h, int s, int v)
{
  uint8 r, g, b;
  convertHSVtoRGB((float)h, s * 0.01f, v * 0.01f, &r, &g, &b);
  shiftLedsForward(r, g, b);
}

// LED 색상을 앞으로 한 칸씩 당기는 함수 (예: 2번 -> 1번, 1번 -> 0번)
void shiftLedsBackward(uint8 r, uint8 g, uint8 b)
{
  // 앞에서부터 뒤로 복사를 진행합니다.
  for (int i = 0; i < NUM_LEDS - 1; i++)
  {
    uint32 destIndex = i * SPI_BYTES_PER_LED;
    uint32 srcIndex = (i + 1) * SPI_BYTES_PER_LED;

    for (int j = 0; j < SPI_BYTES_PER_LED; j++)
    {
      spiTxBuffer[destIndex + j] = spiTxBuffer[srcIndex + j];
    }
  }

  setNeopixelColor(NUM_LEDS - 1, r, g, b);
}

void shiftLedsBackwardHSV(int h, int s, int v)
{
  uint8 r, g, b;
  convertHSVtoRGB((float)h, s * 0.01f, v * 0.01f, &r, &g, &b);
  shiftLedsBackward(r, g, b);
}

// h: 0.0-360.0, s: 0.0-1.0, v: 0.0-1.0
void convertHSVtoRGB(float h, float s, float v, uint8 *r, uint8 *g, uint8 *b)
{
  float c = v * s;
  float x = c * (1.0f - fabs(fmod(h / 60.0f, 2.0f) - 1.0f));
  float m = v - c;
  float r_prime = 0.0f, g_prime = 0.0f, b_prime = 0.0f;

  if (h >= 0.0f && h < 60.0f)
    r_prime = c, g_prime = x, b_prime = 0.0f;
  else if (h >= 60.0f && h < 120.0f)
    r_prime = x, g_prime = c, b_prime = 0.0f;
  else if (h >= 120.0f && h < 180.0f)
    r_prime = 0.0f, g_prime = c, b_prime = x;
  else if (h >= 180.0f && h < 240.0f)
    r_prime = 0.0f, g_prime = x, b_prime = c;
  else if (h >= 240.0f && h < 300.0f)
    r_prime = x, g_prime = 0.0f, b_prime = c;
  else if (h >= 300.0f && h < 360.0f)
    r_prime = c, g_prime = 0.0f, b_prime = x;

  *r = (unsigned char)((r_prime + m) * 255.0f);
  *g = (unsigned char)((g_prime + m) * 255.0f);
  *b = (unsigned char)((b_prime + m) * 255.0f);
}

void initNeopixel(void)
{
  initQSPI();
  setAllLEDColorHSV(0, 0, 0);
}

void transmitNeopixel(void)
{
  IfxQspi_SpiMaster_exchange(&g_qspiDma.spiMasterChannel, spiTxBuffer, NULL_PTR, SPI_BUFFER_SIZE);
}

void setAllLEDColorHSV(int h, int s, int v)
{
  uint8 r, g, b;
  convertHSVtoRGB((float)h, s * 0.01f, v * 0.01f, &r, &g, &b);
  for (int i = 0; i < NUM_LEDS; i++)
  {
    setNeopixelColor(i, r, g, b);
  }
}
