/**********************************************************************************************************************
 * \file Base_Driver_Ds18b20.h
 * \copyright Copyright (C) Infineon Technologies AG 2019
 *
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 *
 * Boost Software License - Version 1.0 - August 17th, 2003
 *
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all
 * derivative works of the Software, unless such copies or derivative works are solely in the form of
 * machine-executable object code generated by a source language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 * IN THE SOFTWARE.
 *********************************************************************************************************************/

#ifndef BASE_DRIVER_DS18B20_H_
#define BASE_DRIVER_DS18B20_H_

/*********************************************************************************************************************/
/*-----------------------------------------------------Includes------------------------------------------------------*/
/*********************************************************************************************************************/
#include "Platform_Types.h"
#include "Base_Com_OneWire.h"

#ifdef __cplusplus
extern "C" {
#endif

/*********************************************************************************************************************/
/*------------------------------------------------------Macros-------------------------------------------------------*/
/*********************************************************************************************************************/
#define BASE_DRIVER_DS18B20_RESET_OK    (0U)

/*********************************************************************************************************************/
/*------------------------------------------------Type Definitions--------------------------------------------------*/
/*********************************************************************************************************************/
typedef enum
{
    BASE_DRIVER_DS18B20_STATE_IDLE = 0,

    /* Temperature conversion sequence */
    BASE_DRIVER_DS18B20_STATE_CONVERT_SEND_RESET,         /* Base_Com_OneWire_Reset(oneWire) */
    BASE_DRIVER_DS18B20_STATE_CONVERT_SEND_SKIP_ROM,      /* Base_Com_OneWire_WriteByte(oneWire, BASE_COM_ONEWIRE_CMD_SKIPROM) */
    BASE_DRIVER_DS18B20_STATE_CONVERT_SEND_CONVERT_T,     /* Base_Com_OneWire_WriteByte(oneWire, DS18B20_CMD_CONVERTTEMP) */
    BASE_DRIVER_DS18B20_STATE_CONVERT_WAIT_CONVERSION,    /* Ds18b20_AllDone(Base_Com_OneWire_t *oneWire) */

    /* Scratchpad read sequence */
    BASE_DRIVER_DS18B20_STATE_READ_SEND_RESET,            /* Base_Com_OneWire_Reset(oneWire) */
    BASE_DRIVER_DS18B20_STATE_READ_SKIP_ROM,              /* Base_Com_OneWire_WriteByte(oneWire, BASE_COM_ONEWIRE_CMD_SKIPROM) */
    BASE_DRIVER_DS18B20_STATE_READ_SEND_READ_SCRATCHPAD,  /* Base_Com_OneWire_WriteByte(oneWire, BASE_COM_ONEWIRE_CMD_RSCRATCHPAD) */
    BASE_DRIVER_DS18B20_STATE_READ_RECEIVE_SCRATCHPAD,    /* scratchpad[i] = Base_Com_OneWire_ReadByte(oneWire) */

    /* Finalization */
    BASE_DRIVER_DS18B20_STATE_POST_READ_RESET,            /* Base_Com_OneWire_Reset(oneWire) */
    BASE_DRIVER_DS18B20_STATE_COMPLETE,
    BASE_DRIVER_DS18B20_STATE_ERROR
} Base_Driver_Ds18b20_State_t;

typedef struct
{
    Base_Driver_Ds18b20_State_t state;
    Base_Com_OneWire_t         *onewire;
    sint16                      temp_x10;
    uint8                       scratchpad[9];
    uint8                       scratchpad_index;
    boolean                     is_busy;
    boolean                     is_data_ready;
    boolean                     is_error;
} Base_Driver_Ds18b20_Context_t;

/*********************************************************************************************************************/
/*------------------------------------------------Function Prototypes------------------------------------------------*/
/*********************************************************************************************************************/
void Base_Driver_Ds18b20_Init(Base_Driver_Ds18b20_Context_t *context);
boolean Base_Driver_Ds18b20_RequestStart(Base_Driver_Ds18b20_Context_t *context);
void Base_Driver_Ds18b20_MainFunction(Base_Driver_Ds18b20_Context_t *context);

boolean Base_Driver_Ds18b20_IsBusy(const Base_Driver_Ds18b20_Context_t *context);
boolean Base_Driver_Ds18b20_IsComplete(const Base_Driver_Ds18b20_Context_t *context);
boolean Base_Driver_Ds18b20_IsError(const Base_Driver_Ds18b20_Context_t *context);

Base_Driver_Ds18b20_State_t Base_Driver_Ds18b20_GetState(
    const Base_Driver_Ds18b20_Context_t *context);

boolean Base_Driver_Ds18b20_GetTemperatureX10(
    const Base_Driver_Ds18b20_Context_t *context,
    sint16                              *temp_x10);

#ifdef __cplusplus
}
#endif

#endif /* BASE_DRIVER_DS18B20_H_ */
