/**********************************************************************************************************************
 * \file Base_Ds18b20_Fsm.h
 * \copyright Copyright (C) Infineon Technologies AG 2019
 * 
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of 
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and 
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all 
 * derivative works of the Software, unless such copies or derivative works are solely in the form of 
 * machine-executable object code generated by a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE 
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN 
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS 
 * IN THE SOFTWARE.
 *********************************************************************************************************************/

#ifndef BASESW_BASE_DS18B20_FSM_H_
#define BASESW_BASE_DS18B20_FSM_H_

#include "Platform_Types.h"
#include "Base_OneWire.h"

#define DS18B20_RESET_OK (0UL)

typedef enum {
    DS18B20_STATE_IDLE = 0,

    /* Temperature conversion sequence */
    DS18B20_STATE_CONVERT_SEND_RESET,          // OneWire_Reset(OneWire)
    DS18B20_STATE_CONVERT_SEND_SKIP_ROM,       // OneWire_WriteByte(OneWire, ONEWIRE_CMD_SKIPROM)
    DS18B20_STATE_CONVERT_SEND_CONVERT_T,      // OneWire_WriteByte(OneWire, DS18B20_CMD_CONVERTTEMP)
    DS18B20_STATE_CONVERT_WAIT_CONVERSION,     // Ds18b20_AllDone(OneWire_t* OneWire) -> OneWire_ReadBit(OneWire)

    /* Scratchpad read sequence */
    DS18B20_STATE_READ_SEND_RESET,             // OneWire_Reset(OneWire)
    DS18B20_STATE_READ_SKIP_ROM,               // OneWire_WriteByte(OneWire, ONEWIRE_CMD_SKIPROM)
    DS18B20_STATE_READ_SEND_READ_SCRATCHPAD,   // OneWire_WriteByte(OneWire, ONEWIRE_CMD_RSCRATCHPAD)
    DS18B20_STATE_READ_RECEIVE_SCRATCHPAD,     // data[i] = OneWire_ReadByte(OneWire) 9번

    /* Finalization */
    DS18B20_STATE_POST_READ_RESET,             // OneWire_Reset(OneWire)
    DS18B20_STATE_COMPLETE,
    DS18B20_STATE_ERROR,
} Ds18b20_State_t;


typedef struct {
    Ds18b20_State_t state;
    OneWire_t*      onewire;
    sint16          temp_x10;
    uint8           scratchpad[9];
    uint8           scratchpad_index;
    boolean         is_busy;
    boolean         is_data_ready;
    boolean         is_error;
} Ds18b20_Context_t;


void             Ds18b20_Fsm_Init(Ds18b20_Context_t* context);
uint8            Ds18b20_Fsm_RequestStart(Ds18b20_Context_t* context);
void             Ds18b20_Fsm_MainFunction(Ds18b20_Context_t* context);

boolean          Ds18b20_Fsm_IsBusy(const Ds18b20_Context_t* context);
boolean          Ds18b20_Fsm_IsComplete(const Ds18b20_Context_t* context);
boolean          Ds18b20_Fsm_IsError(const Ds18b20_Context_t* context);

Ds18b20_State_t  Ds18b20_Fsm_GetState(const Ds18b20_Context_t* context);
boolean          Ds18b20_Fsm_GetTemperatureX10(
                    const Ds18b20_Context_t* context,
                    sint16*                  temp_x10);

#endif /* BASESW_BASE_DS18B20_FSM_H_ */
