/**********************************************************************************************************************
 * \file Flash_EEPROM.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 *
 * Use of this file is subject to the terms of use agreed between (i) you or the
 * company in which ordinary course of business you are acting and (ii) Infineon
 * Technologies AG or its licensees. If and as long as no such terms of use are
 * agreed, use of this file is subject to following:
 *
 * Boost Software License - Version 1.0 - August 17th, 2003
 *
 * Permission is hereby granted, free of charge, to any person or organization
 * obtaining a copy of the software and accompanying documentation covered by
 * this license (the "Software") to use, reproduce, display, distribute,
 * execute, and transmit the Software, and to prepare derivative works of the
 * Software, and to permit third-parties to whom the Software is furnished to do
 * so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including
 * the above license grant, this restriction and the following disclaimer, must
 * be included in all copies of the Software, in whole or in part, and all
 * derivative works of the Software, unless such copies or derivative works are
 * solely in the form of machine-executable object code generated by a source
 * language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 * SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR
 * ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 *********************************************************************************************************************/

/*********************************************************************************************************************/
/*-----------------------------------------------------Includes------------------------------------------------------*/
/*********************************************************************************************************************/

#include "Flash_EEPROM.h"
#include "IfxFlash.h"
#include "IfxScuWdt.h"

/*********************************************************************************************************************/
/*------------------------------------------------------Macros-------------------------------------------------------*/
/*********************************************************************************************************************/

#define DFLASH_START_ADDR 0xAF000000

/*********************************************************************************************************************/
/*-------------------------------------------------Global
 * variables--------------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*--------------------------------------------Private
 * Variables/Constants--------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*------------------------------------------------Function
 * Prototypes------------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*---------------------------------------------Function
 * Implementations----------------------------------------------*/
/*********************************************************************************************************************/

void
Flash_LoadProfileTable (UserProfile_t *outTable)
{
    UserProfile_t *flashData = (UserProfile_t *)DFLASH_START_ADDR;
    for (int i = 0; i < MAX_PROFILES; i++)
    {
        outTable[i] = flashData[i];
    }
}

void
Flash_SaveProfileTable (UserProfile_t *inTable)
{
    uint16 endInitPassword = IfxScuWdt_getSafetyWatchdogPassword();

    IfxScuWdt_clearSafetyEndinit(endInitPassword);
    IfxFlash_eraseMultipleSectors(DFLASH_START_ADDR, 1);
    IfxScuWdt_setSafetyEndinit(endInitPassword);

    IfxFlash_waitUnbusy(0, IfxFlash_FlashType_D0);

    // Table 전체(80바이트)를 4바이트 배열로 casting
    uint32* dataPtr = (uint32*)inTable;

    // 1인당 2 page: 총 10 pages
    int totalPages = MAX_PROFILES * 2;

    for (int page = 0; page < totalPages; page++)
    {
        uint32 pageAddr = DFLASH_START_ADDR + (page * 8);

        IfxFlash_enterPageMode(pageAddr);
        IfxFlash_waitUnbusy(0, IfxFlash_FlashType_D0);

        // 8Bytes씩 읽어 옴
        IfxFlash_loadPage2X32(
            pageAddr, dataPtr[page * 2], dataPtr[page * 2 + 1]);

        IfxScuWdt_clearSafetyEndinit(endInitPassword);
        IfxFlash_writePage(pageAddr);
        IfxScuWdt_setSafetyEndinit(endInitPassword);

        IfxFlash_waitUnbusy(0, IfxFlash_FlashType_D0);
    }
}
